In [1]:
import pandas as pd

In [2]:
data_2020=pd.read_csv("kaggle_survey_2020_responses.csv",low_memory=False, skiprows=1)

data_2021=pd.read_csv("kaggle_survey_2021_responses.csv",low_memory=False, skiprows=1)
data_2022=pd.read_csv("kaggle_survey_2022_responses.csv",low_memory=False, skiprows=1)

In [3]:
data_2020_columns  = set(data_2020.columns)
data_2021_columns  = set(data_2021.columns)
data_2022_columns  = set(data_2022.columns)

In [4]:
len(data_2020_columns), len(data_2021_columns), len(data_2022_columns)

(355, 369, 296)

In [5]:
len(data_2020_columns.intersection(data_2021_columns))

270

In [6]:
len(data_2020_columns.intersection(data_2022_columns))

94

In [7]:
len(data_2021_columns.intersection(data_2022_columns))

111

In [8]:
len(data_2020_columns.intersection(data_2022_columns).intersection(data_2021_columns))

94

In [9]:
data_2020['year'] = 2020
data_2021['year'] = 2021
data_2022['year'] = 2022

In [10]:
data_2020
data_2021
data_2022

,Duration (in seconds),What is your age (# years)?,What is your gender? - Selected Choice,In which country do you currently reside?,"Are you currently a student? (high school, university, or graduate)",On which platforms have you begun or completed data science courses? (Select all that apply) - Selected Choice - Coursera,On which platforms have you begun or completed data science courses? (Select all that apply) - Selected Choice - edX,On which platforms have you begun or completed data science courses? (Select all that apply) - Selected Choice - Kaggle Learn Courses,On which platforms have you begun or completed data science courses? (Select all that apply) - Selected Choice - DataCamp,On which platforms have you begun or completed data science courses? (Select all that apply) - Selected Choice - Fast.ai,...,"Who/what are your favorite media sources that report on data science topics? (Select all that apply) - Selected Choice - Kaggle (notebooks, forums, etc)","Who/what are your favorite media sources that report on data science topics? (Select all that apply) - Selected Choice - Course Forums (forums.fast.ai, Coursera forums, etc)","Who/what are your favorite media sources that report on data science topics? (Select all that apply) - Selected Choice - YouTube (Kaggle YouTube, Cloud AI Adventures, etc)","Who/what are your favorite media sources that report on data science topics? (Select all that apply) - Selected Choice - Podcasts (Chai Time Data Science, O’Reilly Data Show, etc)","Who/what are your favorite media sources that report on data science topics? (Select all that apply) - Selected Choice - Blogs (Towards Data Science, Analytics Vidhya, etc)","Who/what are your favorite media sources that report on data science topics? (Select all that apply) - Selected Choice - Journal Publications (peer-reviewed journals, conference proceedings, etc)","Who/what are your favorite media sources that report on data science topics? (Select all that apply) - Selected Choice - Slack Communities (ods.ai, kagglenoobs, etc)",Who/what are your favorite media sources that report on data science topics? (Select all that apply) - Selected Choice - None,Who/what are your favorite media sources that report on data science topics? (Select all that apply) - Selected Choice - Other,year
0,121,30-34,Man,India,No,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
1,462,30-34,Man,Algeria,No,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
2,293,18-21,Man,Egypt,Yes,Coursera,edX,NaN,DataCamp,NaN,...,"Kaggle (notebooks, forums, etc)",NaN,"YouTube (Kaggle YouTube, Cloud AI Adventures, ...","Podcasts (Chai Time Data Science, O’Reilly Dat...",NaN,NaN,NaN,NaN,NaN,2022
3,851,55-59,Man,France,No,Coursera,NaN,Kaggle Learn Courses,NaN,NaN,...,"Kaggle (notebooks, forums, etc)","Course Forums (forums.fast.ai, Coursera forums...",NaN,NaN,"Blogs (Towards Data Science, Analytics Vidhya,...",NaN,NaN,NaN,NaN,2022
4,232,45-49,Man,India,Yes,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"Blogs (Towards Data Science, Analytics Vidhya,...",NaN,NaN,NaN,NaN,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23992,331,22-24,Man,United States of America,Yes,NaN,NaN,NaN,NaN,NaN,...,"Kaggle (notebooks, forums, etc)",NaN,"YouTube (Kaggle YouTube, Cloud AI Adventures, ...","Podcasts (Chai Time Data Science, O’Reilly Dat...",NaN,"Journal Publications (peer-reviewed journals, ...",NaN,NaN,NaN,2022
23993,330,60-69,Man,United States of America,Yes,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,"YouTube (Kaggle YouTube, Cloud AI Adventures, ...",NaN,NaN,NaN,NaN,NaN,NaN,2022
23994,860,25-29,Man,Turkey,No,NaN,NaN,NaN,DataCamp,NaN,...,"Kaggle (notebooks, forums, etc)",NaN,"YouTube (Kaggle YouTube, Cloud AI Adventures, ...",NaN,NaN,NaN,NaN,NaN,NaN,2022
23995,597,35-39,Woman,Israel,No,NaN,NaN,Kaggle Learn Courses,NaN,NaN,...,NaN,NaN,"YouTube (Kaggle YouTube, Cloud AI Adventures, ...",NaN,NaN,NaN,NaN,NaN,NaN,2022
23996,303,18-21,Man,India,Yes,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other,2022

In [11]:
common_cols = data_2020_columns.intersection(data_2022_columns).intersection(data_2021_columns)

In [12]:
data_20_21_22 = pd.concat([data_2020[list(common_cols)], data_2021[list(common_cols)], data_2022[list(common_cols)]])

In [22]:
c = list(common_cols)
c.append('year')

In [24]:
data_20_21_22 = pd.concat([data_2020[c], data_2021[c], data_2022[c]])

In [26]:
data_20_21_22['year']

0        2020
1        2020
2        2020
3        2020
4        2020
         ...
23992    2022
23993    2022
23994    2022
23995    2022
23996    2022
Name: year, Length: 70006, dtype: int64

In [28]:
data_20_21_22

,What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - C,On which platforms have you begun or completed data science courses? (Select all that apply) - Selected Choice - Udemy,Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice - Tidymodels,Which of the following integrated development environments (IDE's) do you use on a regular basis? (Select all that apply) - Selected Choice - RStudio,"Who/what are your favorite media sources that report on data science topics? (Select all that apply) - Selected Choice - Reddit (r/machinelearning, etc)",On which platforms have you begun or completed data science courses? (Select all that apply) - Selected Choice - Kaggle Learn Courses,On which platforms have you begun or completed data science courses? (Select all that apply) - Selected Choice - LinkedIn Learning,Which of the following ML algorithms do you use on a regular basis? (Select all that apply): - Selected Choice - Linear or Logistic Regression,On which platforms have you begun or completed data science courses? (Select all that apply) - Selected Choice - University Courses (resulting in a university degree),What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - Javascript,...,Which of the following ML algorithms do you use on a regular basis? (Select all that apply): - Selected Choice - Evolutionary Approaches,"Which of the following ML algorithms do you use on a regular basis? (Select all that apply): - Selected Choice - Dense Neural Networks (MLPs, etc)",Which of the following integrated development environments (IDE's) do you use on a regular basis? (Select all that apply) - Selected Choice - Sublime Text,"Who/what are your favorite media sources that report on data science topics? (Select all that apply) - Selected Choice - Podcasts (Chai Time Data Science, O’Reilly Data Show, etc)",Which of the following natural language processing (NLP) methods do you use on a regular basis? (Select all that apply) - Selected Choice - None,Which of the following ML algorithms do you use on a regular basis? (Select all that apply): - Selected Choice - Generative Adversarial Networks,Which categories of computer vision methods do you use on a regular basis? (Select all that apply) - Selected Choice - Other,Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice - Scikit-learn,On which platforms have you begun or completed data science courses? (Select all that apply) - Selected Choice - DataCamp,year
0,C,NaN,NaN,NaN,NaN,Kaggle Learn Courses,NaN,NaN,University Courses (resulting in a university ...,Javascript,...,NaN,"Dense Neural Networks (MLPs, etc)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
1,NaN,Udemy,NaN,NaN,"Reddit (r/machinelearning, etc)",NaN,NaN,Linear or Logistic Regression,NaN,NaN,...,NaN,NaN,Sublime Text,NaN,NaN,NaN,NaN,Scikit-learn,DataCamp,2020
2,NaN,Udemy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Javascript,...,NaN,NaN,Sublime Text,NaN,NaN,NaN,NaN,NaN,NaN,2020
3,NaN,NaN,NaN,NaN,NaN,NaN,LinkedIn Learning,Linear or Logistic Regression,University Courses (resulting in a university ...,NaN,...,NaN,"Dense Neural Networks (MLPs, etc)",NaN,NaN,NaN,NaN,NaN,Scikit-learn,DataCamp,2020
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23992,NaN,NaN,NaN,RStudio,NaN,NaN,NaN,Linear or Logistic Regression,NaN,NaN,...,NaN,NaN,NaN,"Podcasts (Chai Time Data Science, O’Reilly Dat...",NaN,NaN,NaN,Scikit-learn,NaN,2022
23993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Linear or Logistic Regression,University Courses (resulting in a university ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
23994,NaN,Udemy,NaN,NaN,NaN,NaN,NaN,Linear or Logistic Regression,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DataCamp,2022
23995,NaN,NaN,NaN,RStudio,NaN,Kaggle Learn Courses,NaN,NaN,University Courses (resulting in a university ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Scikit-learn,NaN,2022
23996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Linear or Logistic Regression,NaN,Javascript,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Scikit-learn,NaN,2022

In [32]:
data_20_21_22.to_csv('data_20_21_22.csv')